services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - message_broker_network
      - shared_network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
networks:
  message_broker_network:
    driver: bridge
  shared_network:
    external: true
